# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa34126b4aad3e5f54cbc75116d7ba0e74a7145c2894867c8f10eb1540ab9a26d632d81e0196f3949a2c60b6a44b7b32534a684e478d3a035d1009b5ef08264d

test:
  secret_key_base: 441827bbc647378cf25491d6cc983182372e7e58ef666619cfe8e6477f9c02bc2f5ca94bac179ed18a370fdc8208f193f8021b6e86e69633114cfe121d07c2f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
